---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# fail2ban
- include: fail2ban-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_fail2ban_enabled

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
  when: security_fail2ban_enabled

# ssh
- include: ssh.yml

# Autoupdate
- include: autoupdate-RedHat.yml
  when: ansible_os_family == 'RedHat' and security_autoupdate_enabled
